name: 'Set up project'
description: 'Set up project'

inputs:
  node-version:
    description: 'Version Spec of the node version to use.'
    required: true
  npm-version:
    description: 'Version Spec of the npm version to use.'
    required: false
    default: '^10'
  cypress:
    description: 'Install Cypress binary (boolean)'
    type: boolean
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Install Node JS ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    # ❌ npm install step removed

    - name: Install dependencies
      if: ${{ inputs.cypress == 'false' }}
      env:
        CYPRESS_INSTALL_BINARY: 0
      run: |
        echo "skipping cypress binary"
        npm ci
      shell: bash

    - name: Install dependencies (including cypress binary)
      if: ${{ inputs.cypress == 'true' }}
      run: |
        echo "installing cypress binary"
        npm ci
      shell: bash
