env:
  browser: true

parser: "babel-eslint"

parserOptions:
  sourceType: "module"

extends:
  - "standard-jsx"
  - "standard-react"
  - "./.eslintrc-preferred.yml"

settings:
  react:
    version: "16.4"

rules:
  no-console: "error"
