env:
  browser: true

plugins:
  - import
  - react-hooks

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: 'module'

extends:
  - 'standard-jsx'
  - 'standard-react'
  - './.eslintrc.yml'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'

settings:
  react:
    version: '16.8'

rules:
  no-console: 'error'

  import/extensions: ['error', 'never', { 'json': 'always', 'yml': 'always' }]
  react/jsx-sort-props: 'error'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'error'

  '@typescript-eslint/no-unused-vars': ['error', { 'args': 'none' }]

  # Argh.
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-object-literal-type-assertion': 'off'
