env:
  browser: true

plugins:
  - import
  - react-hooks

parser: 'babel-eslint'

parserOptions:
  sourceType: 'module'

extends:
  - 'standard-jsx'
  - 'standard-react'
  - './.eslintrc.yml'

settings:
  react:
    version: '16.4'

rules:
  no-console: 'error'

  import/extensions: ['error', 'never', { 'json': 'always', 'yml': 'always' }]
  react/jsx-sort-props: 'error'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'error'
