env:
  browser: true

plugins:
  - import

parser: "babel-eslint"

parserOptions:
  sourceType: "module"

extends:
  - "standard-jsx"
  - "standard-react"
  - "./.eslintrc.yml"

settings:
  react:
    version: "16.4"

rules:
  no-console: "error"

  import/extensions: ["error", "never", { "json": "always" }]
