export default [
  { id: 'build', name: 'Build', keywords: ['build'] },
  { id: 'coverage', name: 'Code Coverage', keywords: ['coverage'] },
  { id: 'test-results', name: 'Test Results', keywords: ['tests'] },
  { id: 'analysis', name: 'Analysis', keywords: ['analysis'] },
  { id: 'chat', name: 'Chat', keywords: ['chat'] },
  { id: 'dependencies', name: 'Dependencies', keywords: ['dependencies'] },
  { id: 'size', name: 'Size', keywords: ['size'] },
  { id: 'downloads', name: 'Downloads', keywords: ['downloads'] },
  { id: 'funding', name: 'Funding', keywords: ['funding'] },
  { id: 'issue-tracking', name: 'Issue Tracking', keywords: ['issue'] },
  { id: 'license', name: 'License', keywords: ['license'] },
  { id: 'rating', name: 'Rating', keywords: ['rating'] },
  { id: 'social', name: 'Social', keywords: ['social'] },
  { id: 'version', name: 'Version', keywords: ['version'] },
  {
    id: 'platform-support',
    name: 'Platform & Version Support',
    keywords: ['platform'],
  },
  { id: 'monitoring', name: 'Monitoring', keywords: ['monitoring'] },
  { id: 'activity', name: 'Activity', keywords: ['activity'] },
  { id: 'other', name: 'Other', keywords: [] },
]
