export default [
  { id: 'build', name: 'Build' },
  { id: 'coverage', name: 'Code Coverage' },
  { id: 'test-results', name: 'Test Results' },
  { id: 'analysis', name: 'Analysis' },
  { id: 'chat', name: 'Chat' },
  { id: 'dependencies', name: 'Dependencies' },
  { id: 'size', name: 'Size' },
  { id: 'downloads', name: 'Downloads' },
  { id: 'funding', name: 'Funding' },
  { id: 'issue-tracking', name: 'Issue Tracking' },
  { id: 'license', name: 'License' },
  { id: 'rating', name: 'Rating' },
  { id: 'social', name: 'Social' },
  { id: 'version', name: 'Version' },
  {
    id: 'platform-support',
    name: 'Platform & Version Support',
  },
  { id: 'monitoring', name: 'Monitoring' },
  { id: 'activity', name: 'Activity' },
  { id: 'other', name: 'Other' },
]
