name: 'Auto Approve'
description: 'Automatically approve/close selected pull requests for shields.io'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
