# Copy this file to `config/local.yml` and fill it in! It will be gitignored.
public:
  services:
    github:
      baseUri: 'https://api.github.com'
private:
  # The possible values are documented in `doc/server-secrets.md`. Note that
  # you can also set these values through environment variables, which may be
  # preferable for self hosting.
  gh_token: 'SHIELDS_GITHUB_TOKEN'
  gh_client_id: 'GH_CLIENT_ID'
  gh_client_secret: 'GH_CLIENT_SECRET'
