exports['The badge generator SVG should match snapshot 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="26" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="20" fill="#555"/><rect x="13" width="13" height="20" fill="#4c1"/><rect width="26" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="75" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text aria-hidden="true" x="185" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message/label, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="26" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="20" fill="#0f0"/><rect x="13" width="13" height="20" fill="#b3e"/><rect width="26" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="75" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text aria-hidden="true" x="185" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message/label, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="43" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="43" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="30" height="20" fill="#0f0"/><rect x="30" width="13" height="20" fill="#b3e"/><rect width="43" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="245" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="245" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text aria-hidden="true" x="355" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="355" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message only, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="20" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="13" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="0" height="20" fill="#b3e"/><rect x="0" width="13" height="20" fill="#b3e"/><rect width="13" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="65" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="65" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message only, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="31" height="20" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="31" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="0" height="20" fill="#555"/><rect x="0" width="31" height="20" fill="#b3e"/><rect width="31" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="245" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="245" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message only, with logo and labelColor 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="37" height="20" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="37" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="24" height="20" fill="#0f0"/><rect x="24" width="13" height="20" fill="#b3e"/><rect width="37" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="295" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="295" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat" template badge generation should match snapshots: message/label, with links 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" ><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="26" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="20" fill="#0f0"/><rect x="13" width="13" height="20" fill="#b3e"/><rect width="26" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><a target="_blank" xlink:href="https://shields.io/"><rect width="13" x="0" height="20" fill="rgba(0,0,0,0)" /><text aria-hidden="true" x="75" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text></a><a target="_blank" xlink:href="https://www.google.co.uk/"><rect width="13" x="13" height="20" fill="rgba(0,0,0,0)" /><text aria-hidden="true" x="185" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></a></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message/label, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><g shape-rendering="crispEdges"><rect width="13" height="20" fill="#0f0"/><rect x="13" width="13" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text x="75" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message/label, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="43" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><g shape-rendering="crispEdges"><rect width="30" height="20" fill="#0f0"/><rect x="30" width="13" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text x="245" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text x="355" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message only, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="20" role="img" aria-label="grown"><title>grown</title><g shape-rendering="crispEdges"><rect width="0" height="20" fill="#b3e"/><rect x="0" width="13" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text x="65" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message only, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="31" height="20" role="img" aria-label="grown"><title>grown</title><g shape-rendering="crispEdges"><rect width="0" height="20" fill="#555"/><rect x="0" width="31" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text x="245" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message only, with logo and labelColor 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="37" height="20" role="img" aria-label="grown"><title>grown</title><g shape-rendering="crispEdges"><rect width="24" height="20" fill="#0f0"/><rect x="24" width="13" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text x="295" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "flat-square" template badge generation should match snapshots: message/label, with links 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" ><g shape-rendering="crispEdges"><rect width="13" height="20" fill="#0f0"/><rect x="13" width="13" height="20" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><a target="_blank" xlink:href="https://shields.io/"><rect width="13" x="0" height="20" fill="rgba(0,0,0,0)" /><text x="75" y="140" transform="scale(.1)" fill="#fff" textLength="30">cactus</text></a><a target="_blank" xlink:href="https://www.google.co.uk/"><rect width="13" x="13" height="20" fill="rgba(0,0,0,0)" /><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></a></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message/label, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="18" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="26" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="18" fill="#0f0"/><rect x="13" width="13" height="18" fill="#b3e"/><rect width="26" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="75" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="130" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text aria-hidden="true" x="185" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message/label, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="43" height="18" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="43" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="30" height="18" fill="#0f0"/><rect x="30" width="13" height="18" fill="#b3e"/><rect width="43" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="2" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="245" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="245" y="130" transform="scale(.1)" fill="#fff" textLength="30">cactus</text><text aria-hidden="true" x="355" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="355" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message only, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="18" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="13" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="0" height="18" fill="#b3e"/><rect x="0" width="13" height="18" fill="#b3e"/><rect width="13" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="65" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="65" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message only, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="31" height="18" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="31" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="0" height="18" fill="#555"/><rect x="0" width="31" height="18" fill="#b3e"/><rect width="31" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="2" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="245" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="245" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message only, with logo and labelColor 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="37" height="18" role="img" aria-label="grown"><title>grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="37" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="24" height="18" fill="#0f0"/><rect x="24" width="13" height="18" fill="#b3e"/><rect width="37" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="2" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="295" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="295" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator "plastic" template badge generation should match snapshots: message/label, with links 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="18" ><linearGradient id="s" x2="0" y2="100%"><stop offset="0"  stop-color="#fff" stop-opacity=".7"/><stop offset=".1" stop-color="#aaa" stop-opacity=".1"/><stop offset=".9" stop-color="#000" stop-opacity=".3"/><stop offset="1"  stop-color="#000" stop-opacity=".5"/></linearGradient><clipPath id="r"><rect width="26" height="18" rx="4" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="18" fill="#0f0"/><rect x="13" width="13" height="18" fill="#b3e"/><rect width="26" height="18" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><a target="_blank" xlink:href="https://shields.io/"><rect width="13" x="0" height="18" fill="rgba(0,0,0,0)" /><text aria-hidden="true" x="75" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="130" transform="scale(.1)" fill="#fff" textLength="30">cactus</text></a><a target="_blank" xlink:href="https://www.google.co.uk/"><rect width="13" x="13" height="18" fill="rgba(0,0,0,0)" /><text aria-hidden="true" x="185" y="140" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="130" transform="scale(.1)" fill="#fff" textLength="30">grown</text></a></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message/label, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="63.5" height="28" role="img" aria-label="CACTUS: GROWN"><title>CACTUS: GROWN</title><g shape-rendering="crispEdges"><rect width="31" height="28" fill="#0f0"/><rect x="31" width="32.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><text fill="#fff" x="155" y="175" transform="scale(.1)" textLength="70">CACTUS</text><text fill="#fff" x="472.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message/label, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="80.5" height="28" role="img" aria-label="CACTUS: GROWN"><title>CACTUS: GROWN</title><g shape-rendering="crispEdges"><rect width="48" height="28" fill="#0f0"/><rect x="48" width="32.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><image x="9" y="7" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text fill="#fff" x="325" y="175" transform="scale(.1)" textLength="70">CACTUS</text><text fill="#fff" x="642.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message only, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32.5" height="28" role="img" aria-label="GROWN"><title>GROWN</title><g shape-rendering="crispEdges"><rect width="0" height="28" fill="#b3e"/><rect x="0" width="32.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><text fill="#fff" x="162.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message only, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50.5" height="28" role="img" aria-label="GROWN"><title>GROWN</title><g shape-rendering="crispEdges"><rect width="0" height="28" fill="#555"/><rect x="0" width="50.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><image x="9" y="7" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text fill="#fff" x="342.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message only, with logo and labelColor 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="64.5" height="28" role="img" aria-label="GROWN"><title>GROWN</title><g shape-rendering="crispEdges"><rect width="32" height="28" fill="#0f0"/><rect x="32" width="32.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><image x="9" y="7" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text fill="#fff" x="230" y="175" transform="scale(.1)" textLength="-60"></text><text fill="#fff" x="482.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`

exports['The badge generator "for-the-badge" template badge generation should match snapshots: message/label, with links 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="63.5" height="28" ><g shape-rendering="crispEdges"><rect width="31" height="28" fill="#0f0"/><rect x="31" width="32.5" height="28" fill="#b3e"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><a target="_blank" xlink:href="https://shields.io/"><rect width="31" height="28" fill="rgba(0,0,0,0)"/><text fill="#fff" x="155" y="175" transform="scale(.1)" textLength="70">CACTUS</text></a><a target="_blank" xlink:href="https://www.google.co.uk/"><rect width="32.5" height="28" x="31" fill="rgba(0,0,0,0)"/><text fill="#fff" x="472.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></a></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message/label, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="21" height="20" role="img" aria-label="Cactus: grown"><title>Cactus: grown</title><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="5" height="19" rx="2"/><rect x="11.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="11" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M11.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><g aria-hidden="true" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="5" height="19" rx="2" /><text aria-hidden="true" x="25" y="150" fill="#fff" transform="scale(.1)" textLength="-50">Cactus</text><text x="25" y="140" transform="scale(.1)" textLength="-50">Cactus</text><text aria-hidden="true" x="155" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="155" y="140" transform="scale(.1)" textLength="10">grown</text></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message/label, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="191" height="20" role="img" aria-label="Cactus: grown"><title>Cactus: grown</title><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="175" height="19" rx="2"/><rect x="181.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="181" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M181.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><g aria-hidden="true" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="175" height="19" rx="2" /><text aria-hidden="true" x="960" y="150" fill="#fff" transform="scale(.1)" textLength="1480">Cactus</text><text x="960" y="140" transform="scale(.1)" textLength="1480">Cactus</text><text aria-hidden="true" x="1855" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="1855" y="140" transform="scale(.1)" textLength="10">grown</text></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message only, no logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17" height="20" role="img" aria-label="grown"><title>grown</title><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="1" height="19" rx="2"/><rect x="7.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="7" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M7.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><g aria-hidden="true" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="1" height="19" rx="2" /><text aria-hidden="true" x="5" y="150" fill="#fff" transform="scale(.1)" textLength="-90"></text><text x="5" y="140" transform="scale(.1)" textLength="-90"></text><text aria-hidden="true" x="115" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="115" y="140" transform="scale(.1)" textLength="10">grown</text></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message only, with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="157" height="20" role="img" aria-label="grown"><title>grown</title><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="141" height="19" rx="2"/><rect x="147.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="147" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M147.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><g aria-hidden="true" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="141" height="19" rx="2" /><text aria-hidden="true" x="775" y="150" fill="#fff" transform="scale(.1)" textLength="1170"></text><text x="775" y="140" transform="scale(.1)" textLength="1170"></text><text aria-hidden="true" x="1515" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="1515" y="140" transform="scale(.1)" textLength="10">grown</text></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message only, with logo and labelColor 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="157" height="20" role="img" aria-label="grown"><title>grown</title><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="141" height="19" rx="2"/><rect x="147.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="147" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M147.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><g aria-hidden="true" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="141" height="19" rx="2" /><text aria-hidden="true" x="775" y="150" fill="#fff" transform="scale(.1)" textLength="1170"></text><text x="775" y="140" transform="scale(.1)" textLength="1170"></text><text aria-hidden="true" x="1515" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="1515" y="140" transform="scale(.1)" textLength="10">grown</text></g></svg>
`

exports['The badge generator "social" template badge generation should match snapshots: message/label, with links 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="21" height="20" ><style>a:hover #llink{fill:url(#b);stroke:#ccc}a:hover #rlink{fill:#4183c4}</style><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#fcfcfc" stop-opacity="0"/><stop offset="1" stop-opacity=".1"/></linearGradient><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#ccc" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><g stroke="#d5d5d5"><rect stroke="none" fill="#fcfcfc" x="0.5" y="0.5" width="5" height="19" rx="2"/><rect x="11.5" y="0.5" width="9" height="19" rx="2" fill="#fafafa"/><rect x="11" y="7.5" width="0.5" height="5" stroke="#fafafa"/><path d="M11.5 6.5 l-3 3v1 l3 3" stroke="d5d5d5" fill="#fafafa"/></g><g aria-hidden="false" fill="#333" text-anchor="middle" font-family="Helvetica Neue,Helvetica,Arial,sans-serif" text-rendering="geometricPrecision" font-weight="700" font-size="110px" line-height="14px"><a target="_blank" xlink:href="https://shields.io/"><text aria-hidden="true" x="25" y="150" fill="#fff" transform="scale(.1)" textLength="-50">Cactus</text><text x="25" y="140" transform="scale(.1)" textLength="-50">Cactus</text><rect id="llink" stroke="#d5d5d5" fill="url(#a)" x=".5" y=".5" width="5" height="19" rx="2" /></a><a target="_blank" xlink:href="https://www.google.co.uk/"><rect width="10" x="11" height="20" fill="rgba(0,0,0,0)" /><text aria-hidden="true" x="155" y="150" fill="#fff" transform="scale(.1)" textLength="10">grown</text><text id="rlink" x="155" y="140" transform="scale(.1)" textLength="10">grown</text></a></g></svg>
`

exports['The badge generator badges with logos should always produce the same badge badge with logo 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="45" height="20" role="img" aria-label="label: message"><title>label: message</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="45" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="30" height="20" fill="#555"/><rect x="30" width="15" height="20" fill="#4c1"/><rect width="45" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,PHN2ZyB4bWxu"/><text aria-hidden="true" x="245" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">label</text><text x="245" y="140" transform="scale(.1)" fill="#fff" textLength="30">label</text><text aria-hidden="true" x="365" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="50">message</text><text x="365" y="140" transform="scale(.1)" fill="#fff" textLength="50">message</text></g></svg>
`

exports['The badge generator text colors should use black text when the label color is light 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="26" height="20" role="img" aria-label="cactus: grown"><title>cactus: grown</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="26" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="13" height="20" fill="#f3f3f3"/><rect x="13" width="13" height="20" fill="#000"/><rect width="26" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="75" y="150" fill="#ccc" fill-opacity=".3" transform="scale(.1)" textLength="30">cactus</text><text x="75" y="140" transform="scale(.1)" fill="#333" textLength="30">cactus</text><text aria-hidden="true" x="185" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="30">grown</text><text x="185" y="140" transform="scale(.1)" fill="#fff" textLength="30">grown</text></g></svg>
`

exports['The badge generator text colors should use black text when the message color is light 1'] = `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="63.5" height="28" role="img" aria-label="CACTUS: GROWN"><title>CACTUS: GROWN</title><g shape-rendering="crispEdges"><rect width="31" height="28" fill="#000"/><rect x="31" width="32.5" height="28" fill="#e2ffe1"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="100"><text fill="#fff" x="155" y="175" transform="scale(.1)" textLength="70">CACTUS</text><text fill="#333" x="472.5" y="175" font-weight="bold" transform="scale(.1)" textLength="85">GROWN</text></g></svg>
`
