name: Auto approve
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install action dependencies
        run: cd .github/actions/approve-bot && npm ci

      - uses: ./.github/actions/approve-bot
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
