name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  tag-release:
    if: |
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --rfc-3339=date)"

      - name: Checkout branch "master"
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Tag Release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: server-${{ steps.date.outputs.date }}
