name: Frontend
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  test-frontend:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node: [18]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
          cypress: true

      - name: Frontend tests
        run: npm run test:frontend
