name: Integration@node 20
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  test-integration-20:
    runs-on: ubuntu-latest
    env:
      PAT_EXISTS: ${{ secrets.GH_PAT != '' }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 20
        env:
          NPM_CONFIG_ENGINE_STRICT: 'false'

      - name: Integration Tests (with PAT)
        if: ${{ env.PAT_EXISTS == 'true' }}
        uses: ./.github/actions/integration-tests
        with:
          github-token: '${{ secrets.GH_PAT }}'

      - name: Integration Tests (with workflow token)
        if: ${{ env.PAT_EXISTS == 'false' }}
        uses: ./.github/actions/integration-tests
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
